"""
Flask application factory for Nolvus Translator Web UI.
"""
from __future__ import annotations
import logging
import sys
from pathlib import Path

from flask import Flask, Response, request as flask_request

log = logging.getLogger(__name__)


def create_app(config_path: Path | None = None) -> Flask:
    app = Flask(
        __name__,
        template_folder="templates",
        static_folder="static",
        static_url_path="/static",
    )
    app.secret_key = "nolvus-translator-web-ui-2025"

    # ── Load translator config ──────────────────────────────────────────────
    ROOT = Path(__file__).parent.parent.parent
    sys.path.insert(0, str(ROOT))

    try:
        from translator.config import load_config
        cfg_file = config_path or (ROOT / "config.yaml")
        if cfg_file.exists():
            cfg = load_config(cfg_file)
        else:
            cfg = None
            log.warning("config.yaml not found — some features will be disabled")
    except Exception as exc:
        cfg = None
        log.warning(f"Could not load config: {exc}")

    app.config["TRANSLATOR_CFG"] = cfg

    # ── Init mod scanner ────────────────────────────────────────────────────
    if cfg:
        from translator.web.mod_scanner import ModScanner
        scanner = ModScanner(
            mods_dir          = cfg.paths.mods_dir,
            translation_cache = cfg.paths.translation_cache,
            nexus_cache       = cfg.paths.nexus_cache,
        )
    else:
        from translator.web.mod_scanner import ModScanner
        scanner = ModScanner(
            mods_dir          = Path("mods"),
            translation_cache = ROOT / "cache/translation_cache.json",
            nexus_cache       = ROOT / "cache/nexus_cache.json",
        )
    app.config["SCANNER"] = scanner

    # ── Init BSA / SWF string caches ────────────────────────────────────────
    from translator.web.asset_cache import BsaStringCache, SwfStringCache
    _cache_root = cfg.paths.temp_dir if cfg and cfg.paths.temp_dir else ROOT / "temp"
    app.config["BSA_CACHE"] = BsaStringCache(
        cache_root = _cache_root,
        bsarch_exe = str(cfg.paths.bsarch_exe) if cfg and cfg.paths.bsarch_exe else None,
    )
    app.config["SWF_CACHE"] = SwfStringCache(
        cache_root = _cache_root,
        ffdec_jar  = str(cfg.paths.ffdec_jar) if cfg and cfg.paths.ffdec_jar else None,
    )

    # ── Init global text dictionary ──────────────────────────────────────────
    from translator.web.global_dict import GlobalTextDict
    cache_dir = cfg.paths.translation_cache.parent if cfg else ROOT / "cache"
    gd = GlobalTextDict(
        mods_dir   = cfg.paths.mods_dir if cfg else Path("mods"),
        cache_path = cache_dir / "_global_text_dict.json",
    )
    gd.load()  # fast — just reads existing JSON from disk
    app.config["GLOBAL_DICT"] = gd

    # ── Init job manager ────────────────────────────────────────────────────
    from translator.web.job_manager import JobManager
    jm = JobManager.get()
    jobs_file = ROOT / "cache/jobs.json"
    jm.set_persist_path(jobs_file)
    app.config["JOB_MANAGER"] = jm

    # ── Init worker registry (reverse-connected remote workers) ─────────────
    from translator.web.worker_registry import WorkerRegistry
    app.config["WORKER_REGISTRY"] = WorkerRegistry()

    # ── Register blueprints ─────────────────────────────────────────────────
    from translator.web.routes import register_routes
    register_routes(app)

    # ── Remote worker bootstrap script ─────────────────────────────────────
    @app.route("/setup.sh")
    def remote_setup_script():
        """
        Serve a self-contained bash script that sets up the remote worker on
        any macOS or Linux machine and connects it back to this host.

        Usage on the remote:
            curl http://HOST_IP:5000/setup.sh | bash
        """
        host_url  = flask_request.host_url.rstrip("/")   # e.g. http://192.168.1.104:5000
        repo_url  = "https://github.com/codder-cc/skylator.git"
        script = f"""#!/usr/bin/env bash
# Skylator Remote Worker -- one-line bootstrap
# Generated by the Skylator host at {host_url}
# Usage:  curl {host_url}/setup.sh | bash
set -e

HOST_URL="{host_url}"
REPO_URL="{repo_url}"
INSTALL_DIR="$HOME/Documents/skylator"

echo ""
echo "========================================================"
echo "  Skylator Remote Worker -- Automatic Setup"
echo "========================================================"
echo "  Host: $HOST_URL"
echo "  Install: $INSTALL_DIR"
echo ""

# -- Python check -------------------------------------------------------------
if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: python3 not found."
  echo "  macOS:  brew install python"
  echo "  Ubuntu: sudo apt install python3 python3-pip python3-venv"
  exit 1
fi

PY_MIN=310
PY_VER=$(python3 -c "import sys; print(sys.version_info.major*100+sys.version_info.minor)")
if [ "$PY_VER" -lt "$PY_MIN" ]; then
  echo "ERROR: Python 3.10+ required (found $(python3 --version))"
  exit 1
fi
echo "OK  $(python3 --version)"

# -- Clone / update repo ------------------------------------------------------
if [ -d "$INSTALL_DIR/.git" ]; then
  echo "OK  Repo already exists -- pulling latest..."
  git -C "$INSTALL_DIR" pull --ff-only
else
  echo "... Cloning repo -> $INSTALL_DIR"
  git clone "$REPO_URL" "$INSTALL_DIR"
fi

cd "$INSTALL_DIR/remote_worker"

# -- Virtual environment ------------------------------------------------------
if [ ! -d "venv" ]; then
  echo "... Creating virtual environment..."
  python3 -m venv venv
fi
. venv/bin/activate
pip install --upgrade pip --quiet
echo "... Installing base dependencies..."
pip install -r requirements.txt --quiet

# -- Backend detection --------------------------------------------------------
OS_NAME="$(uname -s)"
ARCH="$(uname -m)"

if [ "$OS_NAME" = "Darwin" ]; then
  echo ""
  echo "  macOS detected ($ARCH)"
  if [ "$ARCH" = "arm64" ]; then
    echo "  Installing llama-cpp-python with Metal (Apple Silicon)..."
    CMAKE_ARGS="-DGGML_METAL=on" pip install llama-cpp-python \
      --no-binary llama-cpp-python --quiet \
      && echo "OK  Metal backend installed" \
      || ( echo "  Metal build failed -- trying mlx-lm fallback..."
           pip install mlx-lm --quiet && echo "OK  mlx-lm installed" || echo "WARN backend install failed" )
  else
    echo "  Installing llama-cpp-python (Intel Mac)..."
    pip install llama-cpp-python --quiet \
      && echo "OK  llama-cpp-python installed" \
      || echo "WARN backend install failed -- install manually later"
  fi
elif [ "$OS_NAME" = "Linux" ]; then
  echo ""
  echo "  Linux detected -- installing llama-cpp-python (CUDA 12.x pre-built)..."
  pip install llama-cpp-python \
    --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu124 \
    --quiet \
    && echo "OK  CUDA backend installed" \
    || ( echo "  CUDA wheel failed -- installing CPU fallback..."
         pip install llama-cpp-python --quiet && echo "OK  CPU backend installed" || echo "WARN backend install failed" )
fi

# -- Start worker -------------------------------------------------------------
echo ""
echo "OK  Setup complete -- starting worker..."
echo "    Connecting to: $HOST_URL"
echo "    Press Ctrl+C to stop"
echo ""

exec python server.py --host-url "$HOST_URL"
"""
        return Response(script, mimetype="text/plain; charset=utf-8")

    # ── Jinja2 globals ──────────────────────────────────────────────────────
    import time
    app.jinja_env.globals["time"] = time

    @app.template_filter("humansize")
    def humansize(n: int) -> str:
        for unit in ("B", "KB", "MB", "GB"):
            if n < 1024:
                return f"{n:.1f} {unit}"
            n /= 1024
        return f"{n:.1f} TB"

    @app.template_filter("timeago")
    def timeago(ts: float | None) -> str:
        if not ts:
            return "never"
        delta = time.time() - ts
        if delta < 60:
            return f"{int(delta)}s ago"
        if delta < 3600:
            return f"{int(delta/60)}m ago"
        if delta < 86400:
            return f"{int(delta/3600)}h ago"
        return f"{int(delta/86400)}d ago"

    @app.template_filter("log_class")
    def log_class(line: str) -> str:
        l = line.lower()
        if "[error]" in l or " error " in l:
            return "log-error"
        if "[warning]" in l or " warn " in l:
            return "log-warn"
        if "[info]" in l:
            return "log-info"
        if "[debug]" in l:
            return "log-debug"
        return ""

    return app
