/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TerminologyRouteImport } from './routes/terminology'
import { Route as SingleRouteImport } from './routes/single'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModsIndexRouteImport } from './routes/mods/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as ModsModNameIndexRouteImport } from './routes/mods/$modName/index'
import { Route as ModsModNameStringsRouteImport } from './routes/mods/$modName/strings'
import { Route as ModsModNameContextRouteImport } from './routes/mods/$modName/context'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminologyRoute = TerminologyRouteImport.update({
  id: '/terminology',
  path: '/terminology',
  getParentRoute: () => rootRouteImport,
} as any)
const SingleRoute = SingleRouteImport.update({
  id: '/single',
  path: '/single',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsIndexRoute = ModsIndexRouteImport.update({
  id: '/mods/',
  path: '/mods/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsModNameIndexRoute = ModsModNameIndexRouteImport.update({
  id: '/mods/$modName/',
  path: '/mods/$modName/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsModNameStringsRoute = ModsModNameStringsRouteImport.update({
  id: '/mods/$modName/strings',
  path: '/mods/$modName/strings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsModNameContextRoute = ModsModNameContextRouteImport.update({
  id: '/mods/$modName/context',
  path: '/mods/$modName/context',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/backups': typeof BackupsRoute
  '/config': typeof ConfigRoute
  '/logs': typeof LogsRoute
  '/servers': typeof ServersRoute
  '/single': typeof SingleRoute
  '/terminology': typeof TerminologyRoute
  '/tools': typeof ToolsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/mods/': typeof ModsIndexRoute
  '/mods/$modName/context': typeof ModsModNameContextRoute
  '/mods/$modName/strings': typeof ModsModNameStringsRoute
  '/mods/$modName/': typeof ModsModNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/backups': typeof BackupsRoute
  '/config': typeof ConfigRoute
  '/logs': typeof LogsRoute
  '/servers': typeof ServersRoute
  '/single': typeof SingleRoute
  '/terminology': typeof TerminologyRoute
  '/tools': typeof ToolsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs': typeof JobsIndexRoute
  '/mods': typeof ModsIndexRoute
  '/mods/$modName/context': typeof ModsModNameContextRoute
  '/mods/$modName/strings': typeof ModsModNameStringsRoute
  '/mods/$modName': typeof ModsModNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/backups': typeof BackupsRoute
  '/config': typeof ConfigRoute
  '/logs': typeof LogsRoute
  '/servers': typeof ServersRoute
  '/single': typeof SingleRoute
  '/terminology': typeof TerminologyRoute
  '/tools': typeof ToolsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/mods/': typeof ModsIndexRoute
  '/mods/$modName/context': typeof ModsModNameContextRoute
  '/mods/$modName/strings': typeof ModsModNameStringsRoute
  '/mods/$modName/': typeof ModsModNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/backups'
    | '/config'
    | '/logs'
    | '/servers'
    | '/single'
    | '/terminology'
    | '/tools'
    | '/jobs/$jobId'
    | '/jobs/'
    | '/mods/'
    | '/mods/$modName/context'
    | '/mods/$modName/strings'
    | '/mods/$modName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/backups'
    | '/config'
    | '/logs'
    | '/servers'
    | '/single'
    | '/terminology'
    | '/tools'
    | '/jobs/$jobId'
    | '/jobs'
    | '/mods'
    | '/mods/$modName/context'
    | '/mods/$modName/strings'
    | '/mods/$modName'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/backups'
    | '/config'
    | '/logs'
    | '/servers'
    | '/single'
    | '/terminology'
    | '/tools'
    | '/jobs/$jobId'
    | '/jobs/'
    | '/mods/'
    | '/mods/$modName/context'
    | '/mods/$modName/strings'
    | '/mods/$modName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BackupsRoute: typeof BackupsRoute
  ConfigRoute: typeof ConfigRoute
  LogsRoute: typeof LogsRoute
  ServersRoute: typeof ServersRoute
  SingleRoute: typeof SingleRoute
  TerminologyRoute: typeof TerminologyRoute
  ToolsRoute: typeof ToolsRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ModsIndexRoute: typeof ModsIndexRoute
  ModsModNameContextRoute: typeof ModsModNameContextRoute
  ModsModNameStringsRoute: typeof ModsModNameStringsRoute
  ModsModNameIndexRoute: typeof ModsModNameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminology': {
      id: '/terminology'
      path: '/terminology'
      fullPath: '/terminology'
      preLoaderRoute: typeof TerminologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single': {
      id: '/single'
      path: '/single'
      fullPath: '/single'
      preLoaderRoute: typeof SingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods/': {
      id: '/mods/'
      path: '/mods'
      fullPath: '/mods/'
      preLoaderRoute: typeof ModsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods/$modName/': {
      id: '/mods/$modName/'
      path: '/mods/$modName'
      fullPath: '/mods/$modName/'
      preLoaderRoute: typeof ModsModNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods/$modName/strings': {
      id: '/mods/$modName/strings'
      path: '/mods/$modName/strings'
      fullPath: '/mods/$modName/strings'
      preLoaderRoute: typeof ModsModNameStringsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods/$modName/context': {
      id: '/mods/$modName/context'
      path: '/mods/$modName/context'
      fullPath: '/mods/$modName/context'
      preLoaderRoute: typeof ModsModNameContextRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BackupsRoute: BackupsRoute,
  ConfigRoute: ConfigRoute,
  LogsRoute: LogsRoute,
  ServersRoute: ServersRoute,
  SingleRoute: SingleRoute,
  TerminologyRoute: TerminologyRoute,
  ToolsRoute: ToolsRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  ModsIndexRoute: ModsIndexRoute,
  ModsModNameContextRoute: ModsModNameContextRoute,
  ModsModNameStringsRoute: ModsModNameStringsRoute,
  ModsModNameIndexRoute: ModsModNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
